### ISSUE TITLE
TypeError: '<=' not supported between instances of 'str' and 'NoneType'

### ISSUE THREAD

**Issue by coroneltortuga** [EnterpriseDB/barman#1026]
Our Barman System gehts sporatically this issue for some backups:

TypeError: '<=' not supported between instances of 'str' and 'NoneType'
2024-10-20 12:01:06,829 [124729] barman.cli ERROR: '<=' not supported between instances of 'str' and 'NoneType'
See log file for more details.
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/barman/cli.py", line 2390, in main
    args.func(args)
  File "/usr/lib/python3.11/site-packages/barman/cli.py", line 543, in backup
    server.backup(
  File "/usr/lib/python3.11/site-packages/barman/server.py", line 1610, in backup
    self.check(strategy)
  File "/usr/lib/python3.11/site-packages/barman/server.py", line 609, in check
    self.check_wal_validity(check_strategy)
  File "/usr/lib/python3.11/site-packages/barman/server.py", line 1208, in check_wal_validity
    wal_info = self.get_wal_info(backup_info)

Barman diagnose says:

![image](https://github.com/user-attachments/assets/2bb28130-03ea-4fed-88a3-cee882aac056)

Means that the end Date is not setted correctly (Setted to NONE) but backup marked as WAITING FOR WALS.
That causes that the barman check is not working correctly anymore and no backups can be taken.

**Comment by coroneltortuga** [comment]
Additional information barman backups happen with "barman backup servername --wait" option included on the server which is backuped is currently no bigger traffic

**Comment by martinmarques** [comment]
I don't think we'll be able to help you with so little amount of information. I would at least need the version of Barman. But that might not be enough. Full diagnose would really help (obfuscate any sensible data)

**Comment by coroneltortuga** [comment]
Barman Version: 3.10.0 Barman by EnterpriseDB (www.enterprisedb.com)
My question is, does a backup with WaitingForWALS Switch to Failed after some time or is there any parameter which allows me to set that?
Important is also on the system there is no content to the Database written. And we have a cluster via Repmgr,2 Nodes and ensure a connection over a virtual Ip Adress assigned via keepalived which is switching in Error case between the nodes. That VIP is used as connection point for the barman

**Comment by coroneltortuga** [comment]
Maybe it´s a cool feature request to give and Option for an WAITING for WAL Timeout

**Comment by andremagui** [comment]
Hey @coroneltortuga. Thank you for your patience as we’ve been investigating the issue with your backup. After reviewing your case and analyzing the logs, we have a few observations and potential causes we’d like to discuss.

First of all, to set a timeout for how long the backup will wait for WALs, you can run the command:
`barman backup --wait --wait-timeout SECONDS`.
This will create the backup and wait for WALs for the duration (in SECONDS) specified in the command line.

Even though you have this option above, it seems the issue you're experiencing is related to a missing `end_wal` entry in the **last backup** in the catalog, not the **current backup** being created. When creating a new backup, Barman checks the most recent backup (**last backup**) and fetches WAL information to be used as metadata and for validation for the backup being created.

However, we’re not entirely sure why this happens sporadically in your case, and it’s difficult to pinpoint the exact cause without more detailed logs. It would help if you could provide the full logs for the backup that is exhibiting the issue and also previous ones, including any debug messages Barman might have logged when the problem occurred. This would help us verify the reason why the fields weren’t set.

Additionally, it would be helpful to know:
- Did the backup process encounter any errors or interruptions (e.g., killed process, Ctrl+C, etc.) during the last backup?
- How is the Barman configuration set?
- Is the backups creation automated? Can you provide the history logs?

Once we have more context or log information, we’ll be better positioned to determine the root cause and provide a more accurate solution.
