### ISSUE TITLE
barman.cli ERROR: 'Namespace' object has no attribute 'server_name'

### ISSUE THREAD

**Issue by adewolff** [EnterpriseDB/barman#186]
Hello,
I'm trying to backup a Postgres server using Barman through a streaming-only configuration. WAL streaming seems to work just fine. However, whenever I initiate a `barman backup pg`, the backup will never move past the backup started phase. In the barman.log file I've noticed an error traceback which will get  logged 3 or 4 times in a row when the backup has been running for a bit.
`barman check pg` indicates all OK

Here are the log segments from starting the backup:
```
2018-10-28 17:54:11,546 [32080] barman.backup INFO: Starting backup using postgres method for server pg
 in /var/lib/barman/pg/base/20181028T175411
2018-10-28 17:54:11,558 [32080] barman.backup_executor INFO: Backup start at LSN: A5/430099E0 (00000001000000A500000043, 000099E0)
2018-10-28 17:54:11,558 [32080] barman.backup_executor INFO: Starting backup copy via pg_basebackup for 20181028T175411
2018-10-28 17:54:11,992 [24304] barman.command_wrappers INFO: pg: pg_receivexlog: finished segment at A5/44000000 (timeline 1)
2018-10-28 17:54:25,954 [24304] barman.command_wrappers INFO: pg: pg_receivexlog: finished segment at A5/45000000 (timeline 1)
2018-10-28 17:55:01,855 [32143] barman.wal_archiver INFO: Found 2 xlog segments from streaming for pg. Archive all segments in one run.
2018-10-28 17:55:01,855 [32143] barman.wal_archiver INFO: Archiving segment 1 of 2 from streaming: pg/00000001000000A500000043
2018-10-28 17:55:01,978 [32143] barman.wal_archiver INFO: Archiving segment 2 of 2 from streaming: pg/00000001000000A500000044
```
And here is the error which will show up 3 or 4 times in a row after the backup has been started for a while.
```
2018-10-29 00:12:39,647 [2788] barman.cli ERROR: 'Namespace' object has no attribute 'server_name'
See log file for more details
Traceback (most recent call last):  
  File "/usr/lib/python2.7/dist-packages/barman/cli.py", line 1162, in main
    p.dispatch(pre_call=global_config)
  File "/usr/lib/python2.7/dist-packages/argh/helpers.py", line 55, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/argh/dispatching.py", line 133, in dispatch
    autocomplete(parser)
  File "/usr/lib/python2.7/dist-packages/argh/completion.py", line 92, in autocomplete
    argcomplete.autocomplete(parser)
  File "/usr/lib/python2.7/dist-packages/argcomplete/__init__.py", line 213, in __call__
    completions = self._get_completions(comp_words, cword_prefix, cword_prequote, first_colon_pos)
  File "/usr/lib/python2.7/dist-packages/argcomplete/__init__.py", line 243, in _get_completions
    completions = self.collect_completions(active_parsers, parsed_args, cword_prefix, debug)
  File "/usr/lib/python2.7/dist-packages/argcomplete/__init__.py", line 430, in collect_completions
    completions)
  File "/usr/lib/python2.7/dist-packages/argcomplete/__init__.py", line 372, in _complete_active_option
    prefix=cword_prefix, action=active_action, parsed_args=parsed_args)
  File "/usr/lib/python2.7/dist-packages/barman/cli.py", line 166, in backup_completer
    server = get_server(parsed_args)
  File "/usr/lib/python2.7/dist-packages/barman/cli.py", line 924, in get_server
    name = args.server_name
AttributeError: 'Namespace' object has no attribute 'server_name'
```

**Comment by amenonsen** [comment]
Sorry, this issue got lost in the noise. It's pretty old now, and I can't immediately see how it could happen in the current code. So I'm closing this, but please do reopen with details of your configuration if you can reproduce this with Barman 2.13, which was released recently.
