### ISSUE TITLE
ERROR: 'NoneType' object has no attribute 'ctime'

### ISSUE THREAD

**Issue by mkdel** [EnterpriseDB/barman#276]
Hi,
I have Barman 2.10 on CentOS Linux release 7.7.1908 and a bunch of configured server backups.
It worked fine before 2 days ago I could not execute: barman list-backup all

It fails with the first server from the 'barman list-server' list

2020-04-27 09:09:59,090 [25889] barman.cli ERROR: 'NoneType' object has no attribute 'ctime'
See log file for more details.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/barman/cli.py", line 1355, in main
    p.dispatch(pre_call=global_config)
  File "/usr/lib/python2.7/site-packages/argh/helpers.py", line 55, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/usr/lib/python2.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/usr/lib/python2.7/site-packages/argh/dispatching.py", line 231, in _call
    result = function(namespace_obj)
  File "/usr/lib/python2.7/site-packages/barman/cli.py", line 257, in list_backup
    server.list_backups()
  File "/usr/lib/python2.7/site-packages/barman/server.py", line 1289, in list_backups
    rstatus)
  File "/usr/lib/python2.7/site-packages/barman/output.py", line 301, in result
    _dispatch(_writer, 'result', command, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/barman/output.py", line 174, in _dispatch
    return handler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/barman/output.py", line 621, in result_list_backup
    end_time = backup_info.end_time.ctime()
AttributeError: 'NoneType' object has no attribute 'ctime'

**Comment by mkdel** [comment]
I'm sorry for created issue:
'barman check my-super-postgres-server-name'
showed a root cause:

[barman@postgres-barman ]$ barman check my-super-postgres-server-name
Server my-super-postgres-server-name:
        **PostgreSQL: FAILED**
        directories: OK
        retention policy settings: OK
        backup maximum age: OK (no last_backup_maximum_age provided)
        compression settings: OK
        failed backups: OK (there are 0 failed backups)
        minimum redundancy requirements: OK (have 2 backups, expected at least 0)
        pg_basebackup: OK
        pg_basebackup compatible: OK
        systemid coherence: OK
        archiver errors: OK

pg_hba.conf on my-super-postgres-server-name was messed up. Successfully fixed.

**Comment by amenonsen** [comment]
Hi. Sorry about the lack of response earlier, we're going through old issues now to see if anything still needs dealing with. Please reopen with the backtrace and the contents of the `backup.info` file if you can reproduce this with the current Barman 2.13. Thanks.
