### ISSUE TITLE
archive-command barman-wal-archive yields stack trace "write to closed file"

### ISSUE THREAD

**Issue by srgvg** [EnterpriseDB/barman#315]
Stacktrace in postgres logs when trying the `archive_command` `barman-wal-archive`

The same stacktrace show in the postgres logs, here shown when runnig it manually. (note that the ERROR statement only shows up after several minutes, which must be some kind of timeout?)
```
postgres@gasqlvs01:~/12/main$ barman-wal-archive barmanbackupserver gasqlvs01 pg_wal/000000010000000000000036
ERROR: Error executing ssh: [Errno 32] Broken pipe
Exception ignored in: <function _Stream.__del__ at 0x7f59366793a0>
Traceback (most recent call last):
  File "/usr/lib/python3.8/tarfile.py", line 410, in __del__
    self.close()
  File "/usr/lib/python3.8/tarfile.py", line 458, in close
    self.fileobj.write(self.buf)
ValueError: write to closed file
postgres@gasqlvs01:~/12/main$ Shared connection to barmanbackupserver closed.
```
testing the underlying command that spawns: 
```
postgres@gasqlvs01:~$ ssh  -T barman@juno barman --version
2.12
```
Looking at the barman server, and referencing the right SSH session, I see the connected session. 
```
tcp        0      0 10.1.1.180:22           172.16.1.4:58450        ESTABLISHED 240057/sshd: barman  keepalive (6328.08/0/0)
```
When looking at the process list on the barman server, I see that multiple `put-wal` session/commands remain running, whilst on the database server there are no respective archive processes running, not SSH network sessions active anymore.
```
root      239652  0.0  0.0  14144  9288 ?        Ss   14:42   0:00  \_ sshd: barman [priv]
barman    239742  0.0  0.0  14284  5524 ?        S    14:42   0:00  |   \_ sshd: barman@notty
barman    239743  0.0  0.2  48112 34296 ?        Ss   14:42   0:00  |       \_ /usr/bin/python3 /usr/bin/barman put-wal gasqlvs01
root      240057  0.0  0.0  14140  9224 ?        Ss   14:58   0:00  \_ sshd: barman [priv]
barman    240339  0.0  0.0  14284  5436 ?        S    14:58   0:00  |   \_ sshd: barman@notty
barman    240340  0.0  0.2  48112 34336 ?        Ss   14:58   0:00  |       \_ /usr/bin/python3 /usr/bin/barman put-wal gasqlvs01
root      240592  0.0  0.0  14144  9276 ?        Ss   15:09   0:00  \_ sshd: barman [priv]
barman    240663  0.0  0.0  14284  5556 ?        S    15:09   0:00  |   \_ sshd: barman@notty
barman    240664  0.0  0.2  47912 34476 ?        Ss   15:09   0:00  |       \_ /usr/bin/python3 /usr/bin/barman put-wal gasqlvs01
root      240897  0.0  0.0  14140  9244 ?        Ss   15:14   0:00  \_ sshd: barman [priv]
barman    240968  0.0  0.0  14280  5452 ?        S    15:14   0:00      \_ sshd: barman@notty
barman    240969  0.3  0.2  48112 34292 ?        Ss   15:14   0:00          \_ /usr/bin/python3 /usr/bin/barman put-wal gasqlvs01
```

###  Database Server
postgres@gasqlvs01:~$ /usr/lib/postgresql/12/bin/postgres --version
postgres (PostgreSQL) 12.5 (Ubuntu 12.5-1.pgdg20.04+1)
Ubuntu 20.04.1 LTS

### Barman server
barman 2.12 (2.12-1.pgdg20.04+1)
Ubuntu 20.04.1 LTS

backup list
```
barman@juno:~$ barman list-backup gasqlvs01
gasqlvs01 20201216T230002 - FAILED
gasqlvs01 20201215T150106 - STARTED
gasqlvs01 20201214T142927 - FAILED
```

#### barman check
```
barman@juno:~$ barman check gasqlvs01
Server gasqlvs01:
	PostgreSQL: OK
	superuser or standard user with backup privileges: OK
	PostgreSQL streaming: OK
	wal_level: OK
	replication slot: OK
	directories: OK
	retention policy settings: OK
	backup maximum age: FAILED (interval provided: 1 day, latest backup age: No available backups)
	compression settings: OK
	failed backups: FAILED (there are 2 failed backups)
	minimum redundancy requirements: FAILED (have 0 backups, expected at least 2)
	pg_basebackup: OK
	pg_basebackup compatible: OK
	pg_basebackup supports tablespaces mapping: OK
	systemid coherence: OK
	pg_receivexlog: OK
	pg_receivexlog compatible: OK
	receive-wal running: OK
	archiver errors: OK
```

#### barman diagnose
see https://gist.github.com/srgvg/c4cd38af7545860fc3c74bdeef7325c4

**Comment by srgvg** [comment]
Looks like the issue was network related, although I'm not sure of the deeper cause.

All connections were supposed to go directly within the subnet, but barman server is dual homed, and whilst postgres connections remained local, SSH connections went over a router/firewall. 
Making it connect directly fixed this. Firewall didn't block the SSH connections; MTU is 1500 on every hop.

I'm leaving this open, whilst I follow-this up in the coming days.

**Comment by amenonsen** [comment]
Since this was identified as a network-related problem, I'm closing this.
