### ISSUE TITLE
Barman 2.13: any commands failed on CentOS Linux release 8.4.2105

### ISSUE THREAD

**Issue by grizzlybite** [EnterpriseDB/barman#395]
Hello, team! Thank you for developing barman!

I'am  get the following error when running barman command:
```
[barman@backup ~]$ barman check  test-backup
Server test-backup:
	PostgreSQL: OK
	superuser or standard user with backup privileges: OK
	PostgreSQL streaming: OK
	wal_level: OK
	replication slot: OK
	directories: OK
	retention policy settings: OK
EXCEPTION: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
See log file for more details.
```
```
[barman@backup ~]$ barman list-backup all
EXCEPTION: '<=' not supported between instances of 'str' and 'NoneType'
See log file for more details.
```

```
less /var/log/barman/barman.log

2021-09-13 12:23:54,420 [467080] barman.cli ERROR: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
See log file for more details.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/barman/cli.py", line 1563, in main
    p.dispatch(pre_call=global_config)
  File "/usr/lib/python3.6/site-packages/argh/helpers.py", line 55, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/usr/lib/python3.6/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/usr/lib/python3.6/site-packages/argh/dispatching.py", line 231, in _call
    result = function(namespace_obj)
  File "/usr/lib/python3.6/site-packages/barman/cli.py", line 769, in check
    server.check()
  File "/usr/lib/python3.6/site-packages/barman/server.py", line 570, in check
    self.check_backup_validity(check_strategy)
  File "/usr/lib/python3.6/site-packages/barman/server.py", line 890, in check_backup_validity
    self.config.last_backup_maximum_age
  File "/usr/lib/python3.6/site-packages/barman/backup.py", line 1068, in validate_last_backup_maximum_age
    msg = human_readable_timedelta(now - backup.end_time)
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
```

```
[barman@backup ~]$ barman diagnose
{
    "global": {
        "config": {
            "barman_home": "/mnt/barman",
            "barman_user": "barman",
            "basebackup_retry_sleep": "60",
            "basebackup_retry_times": "5",
            "compression": "gzip",
            "errors_list": [],
            "immediate_checkpoint": "true",
            "last_backup_maximum_age": "7 DAYS",
            "log_file": "/var/log/barman/barman.log",
            "log_level": "DEBUG",
            "path_prefix": "/usr/pgsql-12/bin/"
        },
        "system_info": {
            "barman_ver": "2.13",
            "kernel_ver": "Linux backup 4.18.0-305.12.1.el8_4.x86_64 #1 SMP Wed Aug 11 01:59:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux",
            "python_ver": "Python 3.6.8",
            "release": "RedHat Linux CentOS Linux release 8.4.2105",
            "rsync_ver": "rsync  version 3.1.3  protocol version 31",
            "ssh_ver": "",
            "timestamp": "Mon Sep 13 12:48:49 2021"
        }
    },
    "servers": {
        "test-backup": {
            "backups": {
                "20210828T010026": {
                    "backup_id": "20210828T010026",
                    "backup_label": null,
                    "begin_offset": 15525120,
                    "begin_time": "Sat Aug 28 01:00:25 2021",
                    "begin_wal": "0000000100002CBD000000B9",
                    "begin_xlog": "2CBD/B9ECE500",
                    "config_file": "/var/lib/pgsql/12/data/postgresql.conf",
                    "copy_stats": {
                        "copy_time": 3980.395353,
                        "total_time": 3980.395353
                    },
                    "deduplicated_size": 1774288032497,
                    "end_offset": 11643328,
                    "end_time": "Sat Aug 28 02:06:49 2021",
                    "end_wal": "0000000100002CBD000000D1",
                    "end_xlog": "2CBD/D1B1A9C0",
                    "error": null,
                    "hba_file": "/var/lib/pgsql/12/data/pg_hba.conf",
                    "ident_file": "/var/lib/pgsql/12/data/pg_ident.conf",
                    "included_files": [
                        "/var/lib/pgsql/12/data/database.conf",
                        "/var/lib/pgsql/12/data/pgbadger.conf",
                        "/var/lib/pgsql/12/data/postgresql.auto.conf"
                    ],
                    "mode": "postgres",
                    "pgdata": "/var/lib/pgsql/12/data",
                    "server_name": "test-backup",
                    "size": 1774288032497,
                    "status": "DONE",
                    "systemid": "6790092876325534116",
                    "tablespaces": null,
                    "timeline": 1,
                    "version": 120004,
                    "xlog_segment_size": 16777216
                },
                "20210904T010051": {
                    "backup_id": "20210904T010051",
                    "backup_label": null,
                    "begin_offset": 7130448,
                    "begin_time": "Sat Sep  4 01:00:50 2021",
                    "begin_wal": "0000000100002D7D0000001E",
                    "begin_xlog": "2D7D/1E6CCD50",
                    "config_file": "/var/lib/pgsql/12/data/postgresql.conf",
                    "copy_stats": {
                        "copy_time": 3446.817424,
                        "total_time": 3446.817424
                    },
                    "deduplicated_size": 1781996229075,
                    "end_offset": null,
                    "end_time": null,
                    "end_wal": null,
                    "end_xlog": null,
                    "error": null,
                    "hba_file": "/var/lib/pgsql/12/data/pg_hba.conf",
                    "ident_file": "/var/lib/pgsql/12/data/pg_ident.conf",
                    "included_files": [
                        "/var/lib/pgsql/12/data/database.conf",
                        "/var/lib/pgsql/12/data/pgbadger.conf",
                        "/var/lib/pgsql/12/data/postgresql.auto.conf"
                    ],
                    "mode": "postgres",
                    "pgdata": "/var/lib/pgsql/12/data",
                    "server_name": "test-backup",
                    "size": 1781996229075,
                    "status": "WAITING_FOR_WALS",
                    "systemid": "6790092876325534116",
                    "tablespaces": null,
                    "timeline": 1,
                    "version": 120004,
                    "xlog_segment_size": 16777216
                }
            },
            "config": {
                "active": true,
                "archiver": false,
                "archiver_batch_size": 0,
                "backup_directory": "/mnt/barman/test-backup",
                "backup_method": "postgres",
                "backup_options": "concurrent_backup",
                "bandwidth_limit": null,
                "barman_home": "/mnt/barman",
                "barman_lock_directory": "/mnt/barman",
                "basebackup_retry_sleep": 60,
                "basebackup_retry_times": 5,
                "basebackups_directory": "/mnt/barman/test-backup/base",
                "check_timeout": 30,
                "compression": "gzip",
                "conninfo": "host=10.226.100.58 user=barman dbname=postgres",
                "create_slot": "manual",
                "custom_compression_filter": null,
                "custom_decompression_filter": null,
                "description": "Streaming backup for  backup db",
                "disabled": false,
                "errors_directory": "/mnt/barman/test-backup/errors",
                "immediate_checkpoint": true,
                "incoming_wals_directory": "/mnt/barman/test-backup/incoming",
                "last_backup_maximum_age": "7 days",
                "max_incoming_wals_queue": null,
                "minimum_redundancy": 1,
                "msg_list": [],
                "name": "test-backup",
                "network_compression": false,
                "parallel_jobs": 1,
                "path_prefix": "/usr/pgsql-12/bin/",
                "post_archive_retry_script": null,
                "post_archive_script": null,
                "post_backup_retry_script": null,
                "post_backup_script": null,
                "post_delete_retry_script": null,
                "post_delete_script": null,
                "post_recovery_retry_script": null,
                "post_recovery_script": null,
                "post_wal_delete_retry_script": null,
                "post_wal_delete_script": null,
                "pre_archive_retry_script": null,
                "pre_archive_script": null,
                "pre_backup_retry_script": null,
                "pre_backup_script": null,
                "pre_delete_retry_script": null,
                "pre_delete_script": null,
                "pre_recovery_retry_script": null,
                "pre_recovery_script": null,
                "pre_wal_delete_retry_script": null,
                "pre_wal_delete_script": null,
                "primary_ssh_command": null,
                "recovery_options": "",
                "retention_policy": "window 2 w",
                "retention_policy_mode": "auto",
                "reuse_backup": null,
                "slot_name": "barman",
                "ssh_command": null,
                "streaming_archiver": true,
                "streaming_archiver_batch_size": 0,
                "streaming_archiver_name": "barman_receive_wal",
                "streaming_backup_name": "barman_streaming_backup",
                "streaming_conninfo": "host=10.226.100.58 user=streaming_barman",
                "streaming_wals_directory": "/mnt/barman/test-backup/streaming",
                "tablespace_bandwidth_limit": null,
                "wal_retention_policy": "simple-wal 2 w",
                "wals_directory": "/mnt/barman/test-backup/wals"
            },
            "status": {
                "archive_timeout": 0,
                "checkpoint_timeout": 300,
                "config_file": "/var/lib/pgsql/12/data/postgresql.conf",
                "connection_error": null,
                "current_lsn": "2E7A/61D77A68",
                "current_size": 1724169832213.0,
                "current_xlog": null,
                "data_checksums": "off",
                "data_directory": "/var/lib/pgsql/12/data",
                "has_backup_privileges": true,
                "hba_file": "/var/lib/pgsql/12/data/pg_hba.conf",
                "hot_standby": "on",
                "ident_file": "/var/lib/pgsql/12/data/pg_ident.conf",
                "included_files": [
                    "/var/lib/pgsql/12/data/database.conf",
                    "/var/lib/pgsql/12/data/pgbadger.conf",
                    "/var/lib/pgsql/12/data/postgresql.auto.conf"
                ],
                "is_in_recovery": true,
                "is_superuser": true,
                "max_replication_slots": "6",
                "max_wal_senders": "10",
                "pg_basebackup_bwlimit": true,
                "pg_basebackup_compatible": true,
                "pg_basebackup_installed": true,
                "pg_basebackup_path": "/usr/pgsql-12/bin/pg_basebackup",
                "pg_basebackup_tbls_mapping": true,
                "pg_basebackup_version": "12.8",
                "pg_receivexlog_compatible": true,
                "pg_receivexlog_installed": true,
                "pg_receivexlog_path": "/usr/pgsql-12/bin/pg_receivewal",
                "pg_receivexlog_supports_slots": true,
                "pg_receivexlog_synchronous": false,
                "pg_receivexlog_version": "12.8",
                "pgespresso_installed": false,
                "postgres_systemid": "6790092876325534116",
                "replication_slot": [
                    "barman",
                    true,
                    "2E7A/61000000"
                ],
                "replication_slot_support": true,
                "server_txt_version": "12.4",
                "streaming": true,
                "streaming_supported": true,
                "streaming_systemid": "6790092876325534116",
                "synchronous_standby_names": [
                    ""
                ],
                "timeline": 1,
                "wal_compression": "off",
                "wal_keep_segments": "512",
                "wal_level": "replica",
                "xlog_segment_size": 16777216,
                "xlogpos": "2E7A/61D77A68"
            },
            "wals": {
                "last_archived_wal_per_timeline": {
                    "00000001": {
                        "compression": "gzip",
                        "name": "0000000100002E7A00000052",
                        "size": 4107080,
                        "time": 1631526473.973841
                    }
                }
            }
        }
    }
}
```

**Comment by mikewallace1979** [comment]
Thanks for reporting this @grizzlybite.

At first glance it looks like barman is failing to handle null values in the backup.info file for the backup with ID `20210904T010051`. When running `barman check` barman is reading a value of `None` for the `end_time` in the backup.info file and then trying to [subtract it from a datetime](https://github.com/EnterpriseDB/barman/blob/release/2.13/barman/backup.py#L1063-L1068) instance. When running `barman list-backup`, barman reads the `end_wal` [from the backup.info file](https://github.com/EnterpriseDB/barman/blob/release/2.13/barman/server.py#L1563) and then [fails when attempting to compare it with WAL names in the xlog.db file](https://github.com/EnterpriseDB/barman/blob/release/2.13/barman/server.py#L1589).

The reason why barman does not handle these null values is because these nulls should only occur when a backup is in a `FAILED` state - if a backup is in a `FAILED` state then barman will avoid making these checks altogether and therefore the errors we're seeing here would simply not occur. E.g. barman will only call `get_wal_info` for when listing backups [if the status is WAITING_FOR_WALS or DONE](https://github.com/EnterpriseDB/barman/blob/release/2.13/barman/server.py#L1385) and similarly, [barman retrieves the latest backup](https://github.com/EnterpriseDB/barman/blob/release/2.13/barman/backup.py#L1060) when running `barman check` and the [function which returns this](https://github.com/EnterpriseDB/barman/blob/release/2.13/barman/backup.py#L227) will only look for backups in the [WAITING_FOR_WALS or DONE](https://github.com/EnterpriseDB/barman/blob/release/2.13/barman/backup.py#L67) states.

So I think the underlying bug is the fact that we have a backup in a non-failed state which has null values for `end_wal`, `end_time`, `end_offset` and `end_xlog` - this is something which shouldn't happen.

Your barman diagnose output shows you're using `backup_method = postgres` which means that these missing values should be set using values obtained from the [current_xlog_info](https://github.com/EnterpriseDB/barman/blob/release/2.13/barman/backup_executor.py#L1583-L1585) function. This function is [retrieving WAL information from the postgres server](https://github.com/EnterpriseDB/barman/blob/release/2.13/barman/postgres.py#L619-L622) however if *anything* unexpected happens it will log the error and return `None`. That `None` causes us to skip the call to set the values in `backup.info` and execution proceeds to set the status in the backup.info to `WAITING_FOR_WALS`. This leaves us in the state you report, where `barman check` and `barman list-backup` are attempting to use the `end_time` and `end_wal` values in the backup.info file and causing barman to error out.

The short term workaround for backups which end up in this state is to set the `status` field in the backup.info file to `FAILED` - this will allow the `barman check` and `barman list-backup` commands to work and allow further backups to be taken.

In terms of fixing barman, the current behaviour of [silently proceeding when self.postgres.current_xlog_info](https://github.com/EnterpriseDB/barman/blob/release/2.13/barman/backup_executor.py#L1583) fails should be changed. It's worth noting all other calls to [BackupStrategy._backup_info_from_stop_location](https://github.com/EnterpriseDB/barman/blob/release/2.13/barman/backup_executor.py#L1458) do not check what they are passing to the function (e.g. [here](https://github.com/EnterpriseDB/barman/blob/release/2.13/barman/backup_executor.py#L1650-L1651)), so any errors retrieving the WAL information there would result in an exception, causing the backup to be marked as `FAILED`.

As there is already re-connection logic in the event of a postgres connection failure I think the best approach here is to raise an exception if we cannot determine the [current_xlog_info](https://github.com/EnterpriseDB/barman/blob/release/2.13/barman/backup_executor.py#L1584-L1585).
