### ISSUE TITLE
Exception when using a bad conf file

### ISSUE THREAD

**Issue by tureba** [EnterpriseDB/barman#511]
When using a clearly bad configuration file, Barman throws a python exception. I'd expect only a clear error message, not a python exception. This was distilled from a customer configuration, so fixing the test case will bring a simpler (less scary) message for the end user when they should fix their configuration file.

The following test case was produced in Barman 2.18.

For the obviously wrong configuration file `test.conf`:

```
[barman]
foo = bar

[other]
```

This is the output:

```
$ barman -c test.conf check all
WARNING: Invalid configuration option "foo" in [barman] section.
2022-01-31 22:19:06,357 [31512] barman.config WARNING: Invalid configuration option "foo" in [barman] section.
EXCEPTION: 'NoneType' object has no attribute 'endswith'
See log file for more details.
2022-01-31 22:19:06,360 [31512] barman.cli ERROR: 'NoneType' object has no attribute 'endswith'
See log file for more details.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/barman/cli.py", line 1907, in main
    args.func(args)
  File "/usr/lib/python2.7/site-packages/barman/cli.py", line 956, in check
    servers = get_server_list(args)
  File "/usr/lib/python2.7/site-packages/barman/cli.py", line 1799, in get_server_list
    server_object = Server(conf)
  File "/usr/lib/python2.7/site-packages/barman/server.py", line 247, in __init__
    self.process_manager = ProcessManager(self.config)
  File "/usr/lib/python2.7/site-packages/barman/process.py", line 72, in __init__
    self.config.barman_lock_directory, ".%s-*.lock" % self.config.name
  File "/usr/lib64/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by mikewallace1979** [comment]
I spent some time reproducing this and the specific condition responsible for the stack trace is the absence of a `barman_home` directive - without it Barman sets the value to `None` which then results in paths like `'None/bloop2'` for the backup directory and `None` for barman_lock_directory. This then leads to the rather unpleasant stacktrace in the issue.

I think we therefore need two fixes here:
1. Detect the case where barman_home is not set and exit with a helpful warning.
2. Catch any exception which is raised by the config parsing and print an error instead, logging the full stack trace at debug level.
