### ISSUE TITLE
Allow socket timeout for boto3 streaming responses to be specified

### ISSUE THREAD

**Issue by mikewallace1979** [EnterpriseDB/barman#576]
The default read timeout for the `botocore.response.StreamingBody` used during `barman-cloud-restore` operations from s3 is 60s.

In practice this is not always long enough - if nothing can be read from the underlying socket for longer than 60s then boto3 will raise a `ReadTimeoutError` and close the stream. Because the stream is closed we cannot recover from this error. Any attempt to retry will yield an `IncompleteReadError`.

This can be demonstrated by running the following iptables command while `barman-cloud-restore` is running:

    iptables -A INPUT -p tcp --source-port 443 -j DROP

The following stack traces will be logged after 60s:

```
2022-05-25 10:31:43,807 [14670] ERROR: Barman cloud restore exception: Read timeout on endpoint URL: "None"
2022-05-25 10:31:43,807 [14670] DEBUG: Exception details:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 425, in _error_catcher
    yield
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/usr/lib/python3.8/http/client.py", line 459, in read
    n = self.readinto(b)
  File "/usr/lib/python3.8/http/client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/botocore/response.py", line 78, in read
    chunk = self._raw_stream.read(amt)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 430, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: AWSHTTPSConnectionPool(host='********.s3.amazonaws.com', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/barman/clients/cloud_restore.py", line 69, in main
    downloader.download_backup(
  File "/usr/lib/python3/dist-packages/barman/clients/cloud_restore.py", line 223, in download_backup
    self.cloud_interface.extract_tar(file_info.path, target_dir)
  File "/usr/lib/python3/dist-packages/barman/cloud.py", line 993, in extract_tar
    tf.extractall(path=dst)
  File "/usr/lib/python3.8/tarfile.py", line 2028, in extractall
    self.extract(tarinfo, path, set_attrs=not tarinfo.isdir(),
  File "/usr/lib/python3.8/tarfile.py", line 2069, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "/usr/lib/python3.8/tarfile.py", line 2141, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib/python3.8/tarfile.py", line 2190, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError, bufsize)
  File "/usr/lib/python3.8/tarfile.py", line 247, in copyfileobj
    buf = src.read(bufsize)
  File "/usr/lib/python3.8/tarfile.py", line 521, in read
    buf = self._read(size)
  File "/usr/lib/python3.8/tarfile.py", line 529, in _read
    return self.__read(size)
  File "/usr/lib/python3.8/tarfile.py", line 559, in __read
    buf = self.fileobj.read(self.bufsize)
  File "/usr/lib/python3/dist-packages/barman/cloud_providers/aws_s3.py", line 61, in read
    return self.body.read(n)
  File "/usr/lib/python3/dist-packages/botocore/response.py", line 81, in read
    raise ReadTimeoutError(endpoint_url=e.url, error=e)
botocore.exceptions.ReadTimeoutError: Read timeout on endpoint URL: "None"
```

If we catch the `ReadTimeoutError` and attempt to retry the read in a debugger:

```
(Pdb) self.body.read(n)
*** botocore.exceptions.IncompleteReadError: 69263360 read, but total bytes expected is 13986498560.
(Pdb) self.body._raw_stream.closed
True
```

While raising a timeout is not normally the best solution, in this particular case it is one of few options available given we cannot recover once the timeout has been triggered.

We should therefore add an option to `barman-restore` which allows users to specify their own socket timeout value for the streaming response so that they can set a longer timeout as a workaround for intermittent networking issues. The timeout value can be set [directly on the streaming response](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/response.html#botocore.response.StreamingBody.set_socket_timeout).

It feels like a related issue ought to be filed where we consider how we can make `barman-cloud-restore` more resilient and/or something which can be resumed after partial failure.

**Comment by mikewallace1979** [comment]
The read timeout also affects the other barman cloud commands and some, such as barman-cloud-backup-delete, can exceed the read timeout simply due to the server taking a long time to process the deletion. It should therefore be something which can be specified for any command whenever `--cloud-provider=aws-s3`
