### ISSUE TITLE
Barman commands fail with EXCEPTION: can't compare datetime.datetime to NoneType

### ISSUE THREAD

**Issue by mrudula09attili** [EnterpriseDB/barman#590]
Hello Team,

I am facing issues with barman commands particularly on one server, I have attached the diagnose here and below are the exceptions I am getting

barman list-backup pgsql-host
EXCEPTION: can't compare datetime.datetime to NoneType
See log file for more details. 

**ERRORS from the barman.log**
2022-06-05 03:26:02,556 [117782] barman.cli ERROR: Unable to run cron on server 'pgsql-host', please look in the barman log file for more details.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/barman/cli.py", line 145, in cron
    server.cron()
  File "/usr/lib/python2.7/site-packages/barman/server.py", line 1694, in cron
    self.backup_manager.cron_retention_policy()
  File "/usr/lib/python2.7/site-packages/barman/backup.py", line 578, in cron_retention_policy
    retention_status = self.config.retention_policy.report()
  File "/usr/lib/python2.7/site-packages/barman/retention_policies.py", line 64, in report
    return self._backup_report(source)
  File "/usr/lib/python2.7/site-packages/barman/retention_policies.py", line 296, in _backup_report
    if backups[bid].end_time < self._point_of_recoverability():

barman.cli ERROR: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
See log file for more details.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/barman/cli.py", line 1329, in main
    p.dispatch(pre_call=global_config)
  File "/usr/lib/python2.7/site-packages/argh/helpers.py", line 55, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/usr/lib/python2.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/usr/lib/python2.7/site-packages/argh/dispatching.py", line 231, in _call
    result = function(namespace_obj)
  File "/usr/lib/python2.7/site-packages/barman/cli.py", line 649, in check
    server.check()
  File "/usr/lib/python2.7/site-packages/barman/server.py", line 465, in check
    self.check_backup_validity(check_strategy)
  File "/usr/lib/python2.7/site-packages/barman/server.py", line 762, in check_backup_validity
    self.config.last_backup_maximum_age)
  File "/usr/lib/python2.7/site-packages/barman/backup.py", line 969, in validate_last_backup_maximum_age
    msg = human_readable_timedelta(now - backup.end_time)
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'

Server restart - done
Python lib - reload - done
Still the same error
[barman-diagnose.docx](https://github.com/EnterpriseDB/barman/files/8863127/barman-diagnose.docx)
 
Thanks,
Mrudula

**Comment by mikewallace1979** [comment]
Thanks for reporting the issue Mrudula - the immediate cause is that some of the fields in the backup.info metadata file (end_offset, end_time, end_wal and end_xlog) have values of `None` but the state of the backup is `DONE`. This indicates a bug in Barman since any failure in gathering critical metadata should result in the failure of the backup.

As a short term workaround you could edit the `backup.info` file for the backup with id `20220518T140936` and set the `status` field to `FAILED` - this would stop barman from trying to use those fields and at least enable `barman cron` to function again.

We'll do some further investigation to determine how a backup could have ended up in this state.

In the meantime could you please confirm which version of barman you are using?

**Comment by mrudula09attili** [comment]
Hello Mike,

Oh yes, after editing the backup.info I don't see the error anymore.

Barman version that we are using is 2.7

Thanks,
Mrudula

**Comment by mikewallace1979** [comment]
That's great - at least barman can continue functioning now.

I've taken a look at barman 2.7 and the current version of barman (2.19) to determine how the `backup.info` file could have ended up with a status of `DONE` with an unset `end_time` and `end_wal` value. In this particular case `copy_stats` is also unset which suggests that either the backup failed before it completed or something happened to the `backup.info` file either during or after the backup which caused the metadata to be corrupt. Unfortunately I have not been able to find a way of reproducing the situation.

Do you still have the logs generated by the `barman backup` command which produced backup `20220518T140936`? If you did have those logs, and you were able to share them here, then that might provide some clues as to what happened.
