### ISSUE TITLE
Barman-cloud | RHEL 7 | cannot import Enum

### ISSUE THREAD

**Issue by Ravi160492** [EnterpriseDB/barman#603]
Hi,

I have configured barman 2.19 on RHEL 7.9 and trying to upload backup and wals to Azure blob storage. I have all the required dependent modules installed but still barman-cloud-wal-archive fails with the below error. Attaching a list of pip2 freeze.
[pip_freeze.txt](https://github.com/EnterpriseDB/barman/files/8911300/pip_freeze.txt)

Kindly share what is missing or wrong or if it's a bug. I am using pip 20.1.

Traceback (most recent call last):
  File "/bin/barman-cloud-wal-archive", line 9, in <module>
    load_entry_point('barman==2.19', 'console_scripts', 'barman-cloud-wal-archive')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/barman/clients/cloud_walarchive.py", line 24, in <module>
    from barman.clients.cloud_cli import (
  File "/usr/lib/python2.7/site-packages/barman/clients/cloud_cli.py", line 23, in <module>
    from enum import Enum
ImportError: cannot import name Enum

**Comment by mikewallace1979** [comment]
@Ravi160492 Thanks for reporting the issue here. The source of the issue is [definitely a bug](https://github.com/EnterpriseDB/barman/issues/591) - when we started using `enum` we didn't specify the enum34 module as a dependency for python2. The issue was hidden by the fact that the barman cloud dependencies *did* require enum34 so it was brought in anyway, however clearly there's a secondary issue with enum34 in some environments.

Since we didn't manage to get to the bottom of it on the mailing list I think the best way forward is to just remove enums altogether - we're only using it in one place so can remove it without too much trouble.

Hopefully this change will land in the 3.0.0 release planned for next week.

**Comment by Ravi160492** [comment]
Thanks, @mikewallace1979, I will wait for the new release.
