### ISSUE TITLE
ERROR: Barman cloud backup exception: invalid syntax (__init__.py, line 96)

### ISSUE THREAD

**Issue by WillyRL** [EnterpriseDB/barman#637]
Hi Everyone,

I'm trying to setup Barman with cloud-backup to Minio S3 Compatible Storage

but when executing the barman-cloud-backup command using the required parameters : 
`barman-cloud-backup --cloud-provider aws-s3 -P barman-minio --endpoint-url https://172.31.25.159:32000 s3://barman-backup/ pg` 

Here is the verbose error

```
2022-08-04 08:31:08,079 [15208] ERROR: Barman cloud backup exception: invalid syntax (__init__.py, line 96)
2022-08-04 08:31:08,080 [15208] DEBUG: Exception details:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/barman/clients/cloud_backup.py", line 119, in main
    cloud_interface = get_cloud_interface(config)
  File "/usr/lib/python2.7/site-packages/barman/cloud_providers/__init__.py", line 121, in get_cloud_interface
    return _make_s3_cloud_interface(config, cloud_interface_kwargs)
  File "/usr/lib/python2.7/site-packages/barman/cloud_providers/__init__.py", line 46, in _make_s3_cloud_interface
    from barman.cloud_providers.aws_s3 import S3CloudInterface
  File "/usr/lib/python2.7/site-packages/barman/cloud_providers/aws_s3.py", line 41, in <module>
    import boto3
  File "/usr/lib/python2.7/site-packages/boto3/__init__.py", line 16, in <module>
    from boto3.compat import _warn_deprecated_python
  File "/usr/lib/python2.7/site-packages/boto3/compat.py", line 19, in <module>
    from botocore.vendored import six
  File "/usr/lib/python2.7/site-packages/botocore/__init__.py", line 96
    name = f"{name[: -len(matched)]}{sep}{matched.lower()}"
                                                          ^
SyntaxError: invalid syntax
```

**Comment by mikewallace1979** [comment]
@WillyRL It looks like you're using python2 but have a python3 version of boto3 installed. Try `pip install 'boto3<1.18.0'` to install the most recent boto3 version which is compatible with python2.

**Comment by WillyRL** [comment]
Hi @mikewallace1979 , 

Thank you just fixed it by running the barman using python3.
