### ISSUE TITLE
barman-cloud-backup - fe_sendauth: no password supplied 

### ISSUE THREAD

**Issue by WillyRL** [EnterpriseDB/barman#642]
Using the same configuration, the command `barman-cloud-wal-archive` is working.

But when I'm trying to base backup using `barman-cloud-backup` I'm getting the `fe_sendauth: no password supplied`

```2022-08-05 03:27:07,594 [12031] DEBUG: Event needs-retry.s3.HeadBucket: calling handler <botocore.retryhandler.RetryHandler object at 0x7fe3e8a47ac8>
2022-08-05 03:27:07,594 [12031] DEBUG: No retry needed.
2022-08-05 03:27:07,594 [12031] DEBUG: Event needs-retry.s3.HeadBucket: calling handler <bound method S3RegionRedirector.redirect_from_error of <botocore.utils.S3RegionRedirector object at 0x7fe3e8a47b70>>
2022-08-05 03:27:07,601 [12031] ERROR: Cannot connect to postgres: fe_sendauth: no password supplied
2022-08-05 03:27:07,601 [12031] DEBUG: Exception details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/barman-3.0.1-py3.6.egg/barman/postgres.py", line 162, in connect
    self._conn = psycopg2.connect(self.conninfo)
  File "/usr/local/lib64/python3.6/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: fe_sendauth: no password supplied


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/barman-3.0.1-py3.6.egg/barman/clients/cloud_backup.py", line 167, in main
    postgres.connect()
  File "/usr/local/lib/python3.6/site-packages/barman-3.0.1-py3.6.egg/barman/postgres.py", line 458, in connect
    self._conn = super(PostgreSQLConnection, self).connect()
  File "/usr/local/lib/python3.6/site-packages/barman-3.0.1-py3.6.egg/barman/postgres.py", line 167, in connect
    raise PostgresConnectionError(force_str(e).strip())
barman.exceptions.PostgresConnectionError: fe_sendauth: no password supplied
```

the pg check result
```
WARNING: Invalid configuration option "streaming_archiever" in [pg] section.
WARNING: No archiver enabled for server 'pg'. Please turn on 'archiver', 'streaming_archiver' or both
WARNING: Forcing 'archiver = on'
Server pg:
        WAL archive: FAILED (please make sure WAL shipping is setup)
        PostgreSQL: OK
        superuser or standard user with backup privileges: OK
        PostgreSQL streaming: OK
        wal_level: OK
        directories: OK
        retention policy settings: OK
        backup maximum age: OK (no last_backup_maximum_age provided)
        backup minimum size: OK (0 B)
        wal maximum age: OK (no last_wal_maximum_age provided)
        wal size: OK (0 B)
        compression settings: OK
        failed backups: OK (there are 0 failed backups)
        minimum redundancy requirements: OK (have 0 backups, expected at least 0)
        pg_basebackup: OK
        pg_basebackup compatible: OK
        pg_basebackup supports tablespaces mapping: OK
        systemid coherence: OK (no system Id stored on disk)
        archive_mode: OK
        archive_command: OK
        continuous archiving: FAILED
        archiver errors: OK
```

my pg.conf

```
[pg]
description =  "Main PostgreSQL server"
conninfo = host=ptbc-test-postgres-1 user=barman dbname=postgres
backup_method = postgres
streaming_archiever = on
slot_name = barman
# backup_method = rsync
```

What I've done wrong here? 

Thank you

**Comment by mikewallace1979** [comment]
barman-cloud-backup does not use any barman configuration files so you will need to pass the full conninfo string as the `-d` option to `barman-cloud-backup`.

**Comment by WillyRL** [comment]
Hi @mikewallace1979 , 

I have pass the conninfo and the  `fe_sendauth: no password supplied` is gone now, but the backup stuck, the backup file is not uploaded to the S3 bucket, I have tried it with the minio and the AWS S3

```
...
2022-08-05 08:48:09,004 [5909] DEBUG: Uploading base/16996/3541_fsm
2022-08-05 08:48:09,006 [5909] DEBUG: Uploading base/16996/14037_vm
2022-08-05 08:48:09,008 [5909] DEBUG: Uploading base/16996/14037_fsm
2022-08-05 08:48:09,009 [5909] DEBUG: Uploading base/16996/14022_vm
2022-08-05 08:48:09,011 [5909] DEBUG: Uploading base/16996/14027_vm
2022-08-05 08:48:09,013 [5909] DEBUG: Uploading base/16996/14027_fsm
2022-08-05 08:48:09,015 [5909] DEBUG: Uploading base/16996/14042_vm
2022-08-05 08:48:09,016 [5909] DEBUG: Uploading base/16996/14042_fsm
2022-08-05 08:48:09,018 [5909] DEBUG: Uploading base/16996/14032_vm
2022-08-05 08:48:09,020 [5909] DEBUG: Uploading base/16996/14032_fsm
2022-08-05 08:48:09,021 [5909] DEBUG: Uploading base/16996/14047_vm
2022-08-05 08:48:09,023 [5909] DEBUG: Uploading base/16996/14047_fsm
2022-08-05 08:48:09,038 [5909] DEBUG: Uploading pg_xact/0000
2022-08-05 08:48:09,041 [5909] DEBUG: Uploading pg_logical/replorigin_checkpoint
2022-08-05 08:48:09,047 [5909] INFO: Uploading 'pg_control' file from '/var/lib/pgsql/12/data/global/pg_control' to 'data.tar' with path 'global/pg_control'
2022-08-05 08:48:09,048 [5909] DEBUG: Config file 'postgresql.conf' already in PGDATA
2022-08-05 08:48:09,048 [5909] DEBUG: Config file 'pg_hba.conf' already in PGDATA
2022-08-05 08:48:09,048 [5909] DEBUG: Config file 'pg_ident.conf' already in PGDATA
2022-08-05 08:48:09,048 [5909] INFO: Stopping backup '20220805T084803'
2022-08-05 08:48:09,048 [5909] DEBUG: Stop of native concurrent backup
```

**Comment by mikewallace1979** [comment]
@WillyRL Usually if a backup is stuck while stopping a concurrent backup it's because PostgreSQL is waiting on WAL archiving. Is there anything in the PostgreSQL logs relating to archive command failures around the same time as the backup?

**Comment by WillyRL** [comment]
@mikewallace1979 After I looked up the WAL Archiving log, I found the permission error and fixed it and successfully doing the cloud base backup, but still have `WAL archive: FAILED (please make sure WAL shipping is setup)` in barman check 

```
Server pg:
        WAL archive: FAILED (please make sure WAL shipping is setup)
        PostgreSQL: OK
        superuser or standard user with backup privileges: OK
        PostgreSQL streaming: OK
        wal_level: OK
        replication slot: FAILED (slot 'barman' not initialised: is 'receive-wal' running?)
        directories: OK
        retention policy settings: OK
        backup maximum age: OK (no last_backup_maximum_age provided)
        backup minimum size: OK (0 B)
        wal maximum age: OK (no last_wal_maximum_age provided)
        wal size: OK (0 B)
        compression settings: OK
        failed backups: OK (there are 0 failed backups)
        minimum redundancy requirements: OK (have 0 backups, expected at least 0)
        pg_basebackup: OK
        pg_basebackup compatible: OK
        pg_basebackup supports tablespaces mapping: OK
        systemid coherence: OK (no system Id stored on disk)
        pg_receivexlog: FAILED
        pg_receivexlog compatible: FAILED (PostgreSQL version: 12.11, pg_receivexlog version: None)
        receive-wal running: FAILED (See the Barman log file for more details)
        archive_mode: OK
        archive_command: OK
        continuous archiving: OK
        archiver errors: OK
```
the WAL files are present in the bucket.

**Comment by mikewallace1979** [comment]
`barman check` is checking Barman's local WAL archive and not the bucket.

The reason is because `barman` and the `barman-cloud-*` scripts are really two different things. `barman` is a complete backup/recovery manager which usually runs on a separate server where backups and WALs are stored, while the `barman-cloud-*` scripts are standalone scripts, generally used for moving data and WALs between the cloud and a local PostgreSQL server.

So while Barman can make use of the `barman-cloud-*` scripts as hook scripts, most of its functionality exists to handle the case where it is running on a dedicated host for storing backups and WALs. The WAL archive in the check above is looking in Barman's WAL archive (specifically a file named `xlog.db` which tracks the state of its WAL archive) to see if any WALs have been successfully archived there.

If your goal is to handle backup/recovery entirely with `barman-cloud-*` and S3 then you can ignore `barman check`. If you did also want to archive WALs to Barman then you could do so by configuring [WAL streaming](https://docs.pgbarman.org/release/3.0.1/#wal-streaming).

**Comment by WillyRL** [comment]
Hi, @mikewallace1979 Thank you for the explanation, my goal is to avoid setting up a dedicated instance for the barman, I just need to be able to backup the Postgres to my minio object storage and be able to restore it in my DRC Postgres cluster regularly which has the same setup with the production cluster and have the same replication tool using repmgr. 
I don't see the --reuse parameter to be able to backup only changes in barman-cloud-* scripts.

**Comment by mikewallace1979** [comment]
Ok - sounds like the barman cloud scripts are all you need then.

Unfortunately there is no equivalent to the `--reuse-backup` option in barman cloud. The reuse behaviour in Barman is possible because of the ability of Rsync to detect changed files using the `--copy-dest` or `--link-dest` options - since barman cloud doesn't use Rsync it is unable to offer this feature.

Rather than attempt to add incremental backup support directly in Barman or barman cloud, the long term plan is to take advantage of ongoing efforts in the PostgreSQL community to add incremental backup support to PostgreSQL.
