### ISSUE TITLE
Backup failed with utf-8 codec can't decode byte 0x84 in position 50: invalid start byte

### ISSUE THREAD

**Issue by Kamal-Villupuram** [EnterpriseDB/barman#810]
2023-06-13 11:17:45,192 [10984] barman.cli ERROR: 'utf-8' codec can't decode byte 0x84 in position 50: invalid start byte

See log file for more details.

Traceback (most recent call last):

  File "/pgbin/barman/usr/local/lib/python3.6/site-packages/barman/cli.py", line 2080, in main

    args.func(args)

  File "/pgbin/barman/usr/local/lib/python3.6/site-packages/barman/cli.py", line 487, in backup

    backup_name=args.backup_name,

  File "/pgbin/barman/usr/local/lib/python3.6/site-packages/barman/server.py", line 1502, in backup

    self.backup_manager.remove_wal_before_backup(backup_info)

  File "/pgbin/barman/usr/local/lib/python3.6/site-packages/barman/backup.py", line 1216, in remove_wal_before_backup

    for line in fxlogdb:

  File "/usr/lib64/python3.6/codecs.py", line 321, in decode

    (result, consumed) = self._buffer_decode(data, self.errors, final)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 50: invalid start byte

2023-06-13 11:18:01,610 [11200] barman.config DEBUG: Including configuration file: VCMP1ED.conf

**Comment by Kamal-Villupuram** [comment]
Barman wal archiving is running fine, but backup is failing with above error. Any help is appreciated.
