### ISSUE TITLE
WAL corrupted after enabling compression

### ISSUE THREAD

**Issue by dequede** [EnterpriseDB/barman#820]
Hi all, to save space I have enabled compression = gzip from the conf file for my instance, this way the wals are also compressed once processed. Space is decreased however running barman cron, in the logs, but it errs as follows:

2023-07-10 10:46:14,840 [34309] barman.wal_archiver INFO: Archiving segment 1 of 13378 from file archival: pem/0000000E000007F700000006
2023-07-10 10:46:14,860 [34309] Command WARNING: gzip: stdin: unexpected end of file
2023-07-10 10:46:14,869 [34309] barman.cli ERROR: {'ret': 1, 'out': '', 'err': '\ngzip: stdin: unexpected end of file\n'}
See log file for more details.
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/barman/cli.py", line 2080, in main
args.func(args)
File "/usr/lib/python3.6/site-packages/barman/cli.py", line 1491, in archive_wal
server.archive_wal()
File "/usr/lib/python3.6/site-packages/barman/server.py", line 2502, in archive_wal
self.backup_manager.archive_wal(verbose)
File "/usr/lib/python3.6/site-packages/barman/backup.py", line 822, in archive_wal
archiver.archive(verbose)
File "/usr/lib/python3.6/site-packages/barman/wal_archiver.py", line 213, in archive
self.archive_wal(compressor, wal_info)
File "/usr/lib/python3.6/site-packages/barman/wal_archiver.py", line 326, in archive_wal
dst_file, dst_uncompressed
File "/usr/lib/python3.6/site-packages/barman/compression.py", line 226, in decompress
return self._decompress(src, dst)
File "/usr/lib/python3.6/site-packages/barman/command_wrappers.py", line 261, in call
self.get_output(*args, **kwargs)
File "/usr/lib/python3.6/site-packages/barman/command_wrappers.py", line 293, in get_output
return self._get_output_once(*args, **kwargs)
File "/usr/lib/python3.6/site-packages/barman/command_wrappers.py", line 372, in _get_output_once
self.check_return_value(allowed_retval)
File "/usr/lib/python3.6/site-packages/barman/command_wrappers.py", line 385, in check_return_value
raise CommandFailedException(dict(ret=self.ret, out=self.out, err=self.err))
barman.exceptions.CommandFailedException: {'ret': 1, 'out': '', 'err': '\ngzip: stdin: unexpected end of file\n'}

It also fails changing the compression method. Do you have any tips to be able to re-enable compression so that I can save space? Thanks for the attention!

**Comment by dequede** [comment]
I'm using 3.5 barman on EDB 13.11.

The file exist and is 32K.

Thanks for the attention!

**Comment by dequede** [comment]
For workaround this check i've copied the wal 0000000E000007F700000006 from incoming/ into wals/

But the same problem appens on other wals so the backup cannot be finished.

**Comment by mikewallace1979** [comment]
If the file is greater than 0 bytes and gzip is failing with `gzip: stdin: unexpected end of file)` it suggests that the WAL segment in `<SERVER_DIR>/wals/0000000E000007F7` looks like a valid gzip file but is incomplete.

If you are seeing the same issue with the other WALs then presumably there are similar incomplete WAL files already archived for all `13378` files in `<SERVER_DIR>/incoming` - can you confirm this by listing the contents of `<SERVER_DIR>/wals`?

I am trying to think of scenarios where this could happen but so far I haven't had any success - if you had an existing WAL archive and set `compression = gzip` then Barman should compress the next WAL it copies from `incoming` and all subsequent WALs, and none of those WALs should already be in the archive.

Can you share the complete process you followed, starting from when you had Barman in its original configuration without any compression? If you could share the full Barman config file then that would also be helpful.

**Comment by dequede** [comment]
the postgresql instance is replicating with another node. both master and slave have archiving enabled in barman.conf, and both do so in the same directory on a gluster. Could this be the cause of the problem? Initially it worked perfectly without compression, but since it was enabled at postgresql level with wal_compression = on and on barman.conf with compression = gzip it started giving problems on some wals which therefore do not allow backups.

Below is the configuration of the barman.d/pem.conf:
[pem]
conninfo = host=localhost port=5444 user=enterprisedb dbname=edb
streaming_conninfo = host=inff0macf1010vp user=enterprisedb port=5444
backup_method = postgres
streaming_archiver = on
slot_name = barman_pem
incoming_wals_directory = /backup_pg/barman_pem_1/pem/incoming
archiver=on
path_prefix=/usr/edb/as13/bin

/etc/barman.conf:

; Barman, Backup and Recovery Manager for PostgreSQL
; http://www.pgbarman.org/ - http://www.enterprisedb.com/
;
; Main configuration file

[barman]
; System user
barman_user = enterprisedb

; Directory of configuration files. Place your sections in separate files with .conf extension
; For example place the 'main' server section in /etc/barman.d/main.conf
configuration_files_directory = /etc/barman.d

; Main directory
barman_home = /backup_pg/barman_pem_1

; Locks directory - default: %(barman_home)s
barman_lock_directory = /var/run/barman

; Log location
log_file = /var/log/barman/barman.log

; Log level (see https://docs.python.org/3/library/logging.html#levels)
log_level = INFO

; Default compression level: possible values are None (default), bzip2, gzip, pigz, pygzip or pybzip2
;compression = gzip (now disabled because giving errors)

; Pre/post backup hook scripts
;pre_backup_script = env | grep ^BARMAN
;pre_backup_retry_script = env | grep ^BARMAN
;post_backup_retry_script = env | grep ^BARMAN
;post_backup_script = env | grep ^BARMAN

; Pre/post archive hook scripts
;pre_archive_script = env | grep ^BARMAN
;pre_archive_retry_script = env | grep ^BARMAN
;post_archive_retry_script = env | grep ^BARMAN
;post_archive_script = env | grep ^BARMAN

; Pre/post delete scripts
;pre_delete_script = env | grep ^BARMAN
;pre_delete_retry_script = env | grep ^BARMAN
;post_delete_retry_script = env | grep ^BARMAN
;post_delete_script = env | grep ^BARMAN

; Pre/post wal delete scripts
;pre_wal_delete_script = env | grep ^BARMAN
;pre_wal_delete_retry_script = env | grep ^BARMAN
;post_wal_delete_retry_script = env | grep ^BARMAN
;post_wal_delete_script = env | grep ^BARMAN

; Global bandwidth limit in kilobytes per second - default 0 (meaning no limit)
;bandwidth_limit = 4000

; Number of parallel jobs for backup and recovery via rsync (default 1)
;parallel_jobs = 1

; Immediate checkpoint for backup command - default false
;immediate_checkpoint = false

; Enable network compression for data transfers - default false
;network_compression = false

; Number of retries of data copy during base backup after an error - default 0
;basebackup_retry_times = 0

; Number of seconds of wait after a failed copy, before retrying - default 30
;basebackup_retry_sleep = 30

; Maximum execution time, in seconds, per server
; for a barman check command - default 30
;check_timeout = 30

; Time frame that must contain the latest backup date.
; If the latest backup is older than the time frame, barman check
; command will report an error to the user.
; If empty, the latest backup is always considered valid.
; Syntax for this option is: "i (DAYS | WEEKS | MONTHS | HOURS)" where i is an
; integer > 0 which identifies the number of days | weeks | months of
; validity of the latest backup for this check. Also known as 'smelly backup'.
;last_backup_maximum_age =

; Time frame that must contain the latest WAL file
; If the latest WAL file is older than the time frame, barman check
; command will report an error to the user.
; Syntax for this option is: "i (DAYS | WEEKS | MONTHS | HOURS)" where i is an
; integer > 0
;last_wal_maximum_age =

; Minimum number of required backups (redundancy)
;minimum_redundancy = 1

; Global retention policy (REDUNDANCY or RECOVERY WINDOW)
; Examples of retention policies
; Retention policy (disabled, default)
;retention_policy =
; Retention policy (based on redundancy)
retention_policy = REDUNDANCY 2
; Retention policy (based on recovery window)
;retention_policy = RECOVERY WINDOW OF 7 DAYS


is the same as the slave instance, do you need something else?

**Comment by mikewallace1979** [comment]
Thanks for the response - I have a few more questions:

> the postgresql instance is replicating with another node
> both master and slave have archiving enabled in barman.conf

Am I correct in understanding that both primary and standby have `archive_command` configured to copy WALs to the same Barman `incoming` directory?

What values do `archive_command` and `archive_mode` have on the primary and the standby?

> and both do so in the same directory on a gluster

Are you referring to [GlusterFS](https://www.gluster.org/) here?

> Could this be the cause of the problem? Initially it worked perfectly without compression, but since it was enabled at postgresql level with wal_compression = on and on barman.conf with compression = gzip it started giving problems on some wals which therefore do not allow backups.

I'm still not sure what is going on however setting `wal_compression = on` and using `compression = gzip` in Barman should be ok. PostgreSQL compresses the pages within the WAL and Barman compresses the complete WAL segment - having Barman gzip-compress a WAL segment where the pages are already compressed probably won't save much additional space but it should not result in the errors we're seeing here.

If there are multiple processes archiving the same files to the same `incoming` directory, e.g. both primary and standby are copying WALs to the same Barman server, then it's possible this could cause an issue with the WAL archiving logic applied by Barman when `compression = gzip` is set.

**Comment by martinmarques** [comment]
Hi @dequede , do you have an update on the questions from Mike here, or can we close this issue?
